import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./styles/App.scss"
import Header from "./ui/Header/HeaderIndex";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "The Webfield App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>

          <Header />
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
